### ISSUE TITLE
Logging Suddenly Stops on Production

### ISSUE THREAD

**Issue by pctj101** [dwbutler/logstash-logger#17] opened 2014-08-01 00:42 UTC
So my production server is a puma cluster and it logs perfectly... until recently.

Currently, logging is successful for a number of hours, then suddenly stops.

I traced one cause back to Logstash::Event where Event#to_json was throwing errors on encoding to JSON, and usually that was the last log message.  So I upgraded Logstash::Event to the latest master branch, fixed a couple logstash-event bugs, and the system is much more stable now.
  [ Ref: https://github.com/pctj101/logstash/tree/event_timestamp ]

But... after a few more hours, logging still stops.

So I don't think it's a Logstash::Event#to_json problem any more.

Granted I use lograge to reduce my logs and format into json, but I don't see any problems there either.

And too be fair, I don't see any problems in logstash-logger either.

So it's not clear what to debug.

So while I'm looking into this I thought I'd ask a few simple questions:

  Is there anything in general where a bug could cause some exception to be raised, and permanently disable logstash-logger or Rails.logger until the next server restart?

  Any similar problems seen in the past?

Thanks!So my production server is a puma cluster and it logs perfectly... until recently.

Currently, logging is successful for a number of hours, then suddenly stops.

I traced one cause back to Logstash::Event where Event#to_json was throwing errors on encoding to JSON, and usually that was the last log message.  So I upgraded Logstash::Event to the latest master branch, fixed a couple logstash-event bugs, and the system is much more stable now.
  [ Ref: https://github.com/pctj101/logstash/tree/event_timestamp ]

But... after a few more hours, logging still stops.

So I don't think it's a Logstash::Event#to_json problem any more.

Granted I use lograge to reduce my logs and format into json, but I don't see any problems there either.

And too be fair, I don't see any problems in logstash-logger either.

So it's not clear what to debug.

So while I'm looking into this I thought I'd ask a few simple questions:

  Is there anything in general where a bug could cause some exception to be raised, and permanently disable logstash-logger or Rails.logger until the next server restart?

  Any similar problems seen in the past?

Thanks!

**Comment by chopmo** [comment] 2015-03-20 16:10
@dwbutler It looks like I'm hitting the same issue. 

I'm using MRI 2.2.0, Unicorn 4.5.0, lograge 0.3.1, and logstash-logger 0.8.0. Data is sent to logstash via UDP and also logged to a file: 

```
  config.logstash = [
    {
      type: :file,
      path: 'log/logstash_production.log'
    },
    {
      type: :udp,
      port: 5228,
      host: ENV["LOGSTASH_HOST"]
    }
  ]
```

It looks like you're right about the log level being changed. Really good catch! Printing it reveals that it is raised to 2 for more and more Unicorn workers over time. Restarting the server obviously fixed the problem temporarily. 

So now I'll try to hunt down who is changing the log level. In case you're interested, here is our "impressive" Gemfile.lock: https://gist.github.com/chopmo/88f10097f94db452089f

**Comment by chopmo** [comment] 2015-03-20 16:48
Well that didn't take as long as expected! I'm 99% sure that we found the problem. 

We're using the Savon gem, and when calling `Savon.client` it is possible to pass in a logger object and a log level as options. 

We accidentally passed `Rails.logger` without duplicating it and the `Logger::WARN` leve. Savon changed the level on the logger. 

Simple as that :)

**Comment by dwbutler** [comment] 2015-03-21 02:28
Ouch... It sounds like Savon is not being a good logging citizen. I'll add a note to the Troubleshooting section of the readme. Thanks for the tip!

**Comment by dwbutler** [comment] 2015-03-21 21:36
I added a general note about gems changing the log level to the Troubleshooting section and linked to this issue. I think it's been well-established that this issue is caused by other gems. I can't think of any good way to protect one's logger level from getting stomped. So I'm going to close this issue.

If anyone find another gem causing a problem, or has any ideas about how to protect the log level from getting changed, feel free to add more comments to this issue.

**Closed by dwbutler** 2015-03-21 21:36 UTC

**Comment by glaszig** [comment] 2016-12-21 01:38
i'm also suffering this. i even followed [instructions in a book](https://books.google.de/books?id=w5QfDAAAQBAJ&lpg=PA480&dq=lograge%20logstash&pg=PA482#v=onepage&q&f=false).
it describes how to use lograge and logstash-logger to send logs off to logstash but logs are only being sent to logstash when restarting the server (apache + passener).
this looks to me like some sort of buffering issue and indeed if i set the `sync: true` option in the `LogStashLogger` initializer, logs land in my logstash.

the buffer by default is supposed to collect up to 50 messages and flush them every 5 seconds. but it doesn't for my case. anything i'm missing?

```rb
Rails.application.configure do
  config.lograge.enabled = true
  config.lograge.custom_options = lambda do |event|
    exceptions = %w(controller action format id)
    {
      params:      event.payload[:params].except(*exceptions).to_json,
      type:        :rails,
      environment: Rails.env
    }
  end
  config.lograge.formatter = Lograge::Formatters::Logstash.new
  config.lograge.logger    = LogStashLogger.new uri: 'udp://logstash-server:1234'
end
```

**Comment by dwbutler** [comment] 2016-12-21 02:30
@glaszig I noticed that you are using UDP output. Based on the symptoms you're describing, I believe you are observing normal Ruby behavior. When Ruby writes to an IO device such as a file or socket, it doesn't write immediately. It keeps it's own internal buffer and flushes it "periodically." If you write infrequently enough and don't have enough memory pressure, "periodically" could mean "never." Ruby will, of course, flush all buffers when you exit the program (which is what happens when you restart the server). The only way to control this behavior is to set `sync=true`, as you did. I'll make a note of this behavior in the readme.

**Comment by glaszig** [comment] 2016-12-21 02:34
sorry, i didn't know enough about these kind of ruby internals but i was imagining something like that. there is indeed very low traffic on this system. thanks for getting back.

**Comment by glaszig** [comment] 2016-12-22 16:22
if anybody else comes across this and is interested in ruby's io buffering: http://www.jstorimer.com/blogs/workingwithcode/7766075-screencast-rubys-io-buffering-and-you

**Comment by lloydwatkin** [comment] 2018-05-22 08:31
Hi, I believe I'm hitting this issue now myself (boo!). Everything is fine on staging, but as soon as I get to production, nada.

Are there any tips/tools that would allow me to search through all my gem dependencies to find the culprit or is it just a case of lots of searching?
