### ISSUE TITLE
Bug: LogStashLogger::Device::UDP - Errno::EMSGSIZE - Message too long

### ISSUE THREAD

**Issue by collimarco** [dwbutler/logstash-logger#78] opened 2016-06-13 18:30 UTC
Related to #75 #71 

I have spent the whole day in order to figure out what was making the request hang forever on my server and I've finally find out that it is a bug in this gem.

In fact I've been able to reproduce the error from the rails console.

The error only happens when an SQL query is very long (and thus the log message produced).

You get **many** of the following errors if the log message is long:

```
Bug: LogStashLogger::Device::UDP - Errno::EMSGSIZE - Message too long
```

**Comment by dwbutler** [comment] 2016-06-16 06:05
According to my research, UDP has a maximum limit of about 64K. There isn't any good way to send the message in chunks because packets can arrive out of order.

This should probably be documented as a known limitation in the UDP output. It would probably also be reasonable to truncate the message.

**Comment by collimarco** [comment] 2016-06-16 06:21
Yes I think that truncating the string and documenting it would be the best solution.

**Comment by anothermh** [comment] 2016-06-17 23:10
The maximum size supported for UDP for the UDPSocket class is 9217 bytes. You can verify this simply:

```
UDPSocket.new.send "0"*9216, 0, "127.0.0.1", 5228
9216
UDPSocket.new.send "0"*9217, 0, "127.0.0.1", 5228
Errno::EMSGSIZE: Message too long - sendto(2) for "127.0.0.1" port 5228
```

The problem is explained in more detail here; it's an infinite loop in the `Stud::Buffer` module: https://github.com/jordansissel/ruby-stud/issues/28

This is my ugly monkeypatch for https://github.com/dwbutler/logstash-logger/blob/506eb271caa63f0e25deb61f911a3150d9f82277/lib/logstash-logger/device/connectable.rb; it works for me because I use UDP and JSON exclusively with logstash, and I am willing to trim logged messages. Not everyone will be in the same boat.

```ruby
      def write(message)
        if self.class.name == "LogStashLogger::Device::UDP" && message.bytesize >= 9217
          begin
            json = MultiJson.load(message)
          rescue MultiJson::ParseError => e
            json = { "message" => "" }
          end

          json["message"] = json["message"].byteslice(0..8192)

          begin
            message = MultiJson.dump(json)
          rescue MultiJson::ParseError => e
            message = ""
          end
        end
        buffer_receive message
        buffer_flush(force: true) if @sync
      end
```

I could not find any other reasonable place inside this gem to catch and trim the message body, but I didn't spend a ton of time searching. If you have a better idea I would be happy to help, as I rely heavily on this gem for production use and this bug causes a DoS.

**Comment by dwbutler** [comment] 2016-06-18 06:36
@anothermh Thanks for the patch. After some thinking and looking over the architecture, I decided that the best approach would be to let the user limit the size of the message. (See #80). This is benefits beyond mitigating the UDP issue - it can also help mitigate a DOS attack where the application is logging untrusted user input.

If this solution looks good to you, I'll add some documentation and release it.

**Comment by anothermh** [comment] 2016-06-18 18:01
It looks good to me. The only issue I see is that the message field is not the only field in the payload, so users will have to estimate the byte size of the other fields to determine an appropriate maximum byte size for the message field. In my case I went with 8192 for the message, leaving about 1k for the other fields.

**Comment by collimarco** [comment] 2016-06-19 07:30
Maybe you can define a method that produces the json (probably it already exists).

Then you generate the json:

- if the total length is ok then you proceed
- otherwise you calculate the `diff =  max_length - json_length`, you truncate the message accordingly (not the json) and you generate the json again

**Comment by ktreis** [comment] 2016-07-01 02:01
I worked around this with something like this:

```ruby
MAX_MESSAGE_SIZE = 1000
LogStashLogger.configure do |config|
  config.customize_event do |event|
    if event['message'] && event['message'].size > MAX_MESSAGE_SIZE
      event['message'] = event['message'][0..MAX_MESSAGE_SIZE-1] + '...'
      event['message_truncated'] = true
    end
  end
end

**Closed** 2016-07-11 17:53 UTC
Labels: bug
